name: burgdelivery
services:
- name: burgdelivery-web
  source_dir: /
  github:
    repo: andryus/burgdelivery
    branch: main
  build_command: npm install && npm run build
  run_command: npm start
  http_port: 3000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_PIX_API_KEY
    type: SECRET
  - key: VITE_PIX_PRODUCT_HASH
    type: SECRET
  - key: VITE_PIX_ACCOUNT_ID
    value: "4176"
  - key: VITE_PIX_API_URL
    value: https://multi.paradisepags.com/api/v1
  - key: VITE_CPF_API_KEY
    type: SECRET
  - key: VITE_CPF_API_KEY_2
    type: SECRET
